//! Automatically generated by [`error-chain`](https://crates.io/crates/error-chain).

error_chain! {
    foreign_links {
        Io(::std::io::Error) #[doc = "For IO-related errors."];
        Json(::serde_json::Error) #[doc = "For errors from parsing JSON."];
        //Http(::hyper::Error);
        //Tls(::native_tls::Error);
        //Mysql(::mysql::Error);
        //PostgresDbConnect(::postgres::error::ConnectError);
        //DbPool(::r2d2::InitializationError);
        //OneshotDropped(::futures::sync::oneshot::Canceled);
        //Toml(::toml::de::Error);
    }
}