[package]
name = "ayase_chan"
version = "0.1.0"
authors = ["r3c0d3x <r3c0d3x@airmail.cc>"]

[dependencies]
futures = "0.1"
serde = "1"
serde_derive = "1"
shamrock = { version = "0.1", path = "../shamrock" }